from __future__ import annotations
from pathlib import Path
import json
from jinja2 import Environment,BaseLoader,select_autoescape
from .models import Severity
TEMPLATE='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FIREWATCH Report</title><style>body{font:14px system-ui;background:#09111f;color:#e7eefb;margin:0}.wrap{max-width:1200px;margin:auto;padding:28px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#111d30;border:1px solid #263851;border-radius:12px;padding:16px;margin:12px 0}.sev{padding:3px 8px;border-radius:20px;font-weight:700}.critical{background:#7f1d1d}.high{background:#9a3412}.medium{background:#92400e}.low{background:#1d4ed8}.info{background:#475569}.mono{font-family:ui-monospace,monospace;word-break:break-all}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #263851;text-align:left;vertical-align:top}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}</style></head><body><div class="wrap"><h1>FIREWATCH Web Security Report</h1><p>Target: <span class="mono">{{target}}</span></p><div class="grid">{% for s in severities %}<div class="card"><div class="sev {{s}}">{{s|upper}}</div><h2>{{counts[s]}}</h2></div>{% endfor %}</div><div class="card"><h2>Coverage</h2><table><tr><th>Phase</th><th>Status</th><th>Details</th></tr>{% for x in coverage %}<tr><td>{{x.phase}}</td><td>{{x.status}}</td><td>{{x.details}}</td></tr>{% endfor %}</table></div><div class="card"><h2>Findings</h2>{% for f in findings %}<section class="card"><h3>{{f.title}} <span class="sev {{f.severity}}">{{f.severity|upper}}</span></h3><p><b>Rule:</b> {{f.rule_id}} &nbsp; <b>Confidence:</b> {{f.confidence}}% &nbsp; <b>Risk:</b> {{f.risk}}</p><p><b>Endpoint:</b> <span class="mono">{{f.endpoint}}</span></p><p>{{f.description}}</p><p><b>Impact:</b> {{f.impact}}</p><p><b>Evidence:</b> {{f.evidence}}</p><p><b>Remediation:</b> {{f.remediation}}</p><p><b>References:</b> {{f.references}}</p></section>{% endfor %}</div></div></body></html>'''
def render(scan,findings,events,output_path,coverage):
    findings=list(findings); counts={s.value:sum(1 for f in findings if f.severity==s) for s in Severity}
    payload=[]
    for f in findings: payload.append({'id':f.id,'rule_id':f.rule_id,'category':f.category,'title':f.title,'severity':f.severity.value,'confidence':round(f.confidence*100),'risk':f.risk_score,'status':f.status.value,'endpoint':f.endpoint,'description':f.description,'impact':f.impact,'remediation':f.remediation,'evidence':f.evidence_summary,'references':', '.join(f.references)})
    env=Environment(loader=BaseLoader(),autoescape=select_autoescape(['html','xml']))
    html=env.from_string(TEMPLATE).render(target=scan.target_url,counts=counts,severities=[s.value for s in Severity],findings=payload,coverage=coverage)
    Path(output_path).write_text(html,encoding='utf-8')
def render_json(scan,findings,events,output_path,coverage):
    Path(output_path).write_text(json.dumps({'meta':{'version':'2.0.0','scan_id':scan.id,'target':scan.target_url,'status':scan.status.value},'coverage':coverage,'events':[{'phase':e.phase,'message':e.message,'progress':e.progress,'created_at':e.created_at.isoformat()} for e in events],'findings':[{'id':f.id,'rule_id':f.rule_id,'category':f.category,'title':f.title,'severity':f.severity.value,'confidence':f.confidence,'risk_score':f.risk_score,'status':f.status.value,'endpoint':f.endpoint,'description':f.description,'impact':f.impact,'remediation':f.remediation,'evidence_summary':f.evidence_summary,'references':f.references} for f in findings]},ensure_ascii=False,indent=2),encoding='utf-8')
